FROM ubuntu

LABEL maintainer="gmolin@student.hive.fi"
RUN apt-get update && apt-get upgrade -y && apt-get install -y default-jdk default-jre git vim emacs

# How to build it?
# docker build -t b01 .

# How to run it?
# docker run --rm -ti b01