FROM debian:latest

LABEL maintainer="gmolin@student.hive.fi"

RUN apt-get update && apt-get upgrade -y && apt-get install -y build-essential git emacs vim

# How to build it?
# docker build -t b03 .

# How to run it?
# docker run --rm -ti b03